name: Shellcheck
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - name: Run shellcheck.
              run: ./setup.sh release
