name: shellcheck
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - name: Run shellcheck.
              shell: sh
              run: ./configure.sh -s && ./configure.sh -r
