name: party_stopper
on: [pull_request]
branches: ${{ github.head_ref }}
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
			      with:
			        ref: ${{ github.event.pull_request.head.sha }}
            - name: Run shellcheck.
              run: ./setup/setup.sh release
